# This configuration is fetched from https://github.com/klakegg/docker-hugo.
# Please create an issue or pull request in the repository if you want to contribute.

name: Build website

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: klakegg/hugo:${HUGO_VERSION}-ext-debian

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Set this to 'true' or 'recursive' if you use submodules
        submodules: false 

    - name: Fetch npm dependencies
      run: (test -e package.json && npm install) || echo "package.json does not exists, skippeing this step."

    - name: Build
      run: hugo --minify

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: src/public


  verify:
    name: Verify
    runs-on: ubuntu-latest
    container: klakegg/html-proofer:latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: site

      - name: HTML-Proofer
        # Set this to 'true' if you don't want to fail the build in this step.
        continue-on-error: false
        run: htmlproofer --allow-hash-href --check-html --empty-alt-ignore


  #deploy:
  #  name: Deploy
  #  runs-on: ubuntu-latest
  #  needs: verify