# This configuration is fetched from https://github.com/klakegg/docker-hugo.
# Please create an issue or pull request in the repository if you want to contribute.

name: Build website

on: [push]

jobs:
  hugo:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Set this to 'true' or 'recursive' if you use submodules
        submodules: false 

    # Uncomment if you need to install npm dependencies
    #- name: Fetch npm dependencies
    #  run: npm install

    - name: Build
      run: |
        docker run --rm -i \
          -v $(pwd):/src \
          klakegg/hugo:${HUGO_VERSION}-ext-debian
