name: Alpine (standard)

images:
  # Alpine + Hugo
  alpine:
    target: alpine
    alias:
      - $(VERSION)-alpine
    tests:
      - hugo

  # Alpine + Hugo + CI
  alpine-ci:
    target: alpine--ci
    alias:
      - $(VERSION)-alpine-ci

tests:
  hugo:
    command: version
    expected: Hugo

