name: Alpine (extended)

images:
  # Alpine + Hugo extended
  ext-alpine:
    target: ext-alpine
    edge: true
    alias:
      - $(VERSION)-ext-alpine
    tests:
      - hugo
      - golang
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + CI
  ext-alpine-ci:
    target: ext-alpine--ci
    edge: true
    alias:
      - $(VERSION)-ext-alpine-ci
    platforms:
      - linux/amd64

tests:
  hugo:
    command: version
    expected: Hugo

  golang:
    entrypoint: go
    command: version
    expected: go version
