name: Docker build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    #- name: Set up Docker Buildx
    #  id: buildx
    #  uses: crazy-max/ghaction-docker-buildx@v3
    #  with:
    #    buildx-version: latest
    #    qemu-version: latest

    - name: Build
      run: make build-docker

    - name: Test Docsy
      run: make test-docsy

    - name: Test DocuAPI
      run: make test-docuapi

    - name: Push egde images
      if: "!startsWith(github.ref, 'refs/tags/')"
      env:
        DOCKER_USERNAME: klakegg
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: make edge-tag edge-push

    - name: Push images
      if: "startsWith(github.ref, 'refs/tags/')"
      env:
        DOCKER_USERNAME: klakegg
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: make release-push
