name: Docker build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare templates
      run: make build-templates

    - name: Build
      run: make build-docker-debug

    - name: Test Docsy
      run: make test-docsy

    - name: Test DocuAPI
      run: make test-docuapi

    - name: Push egde images
      if: "!startsWith(github.ref, 'refs/tags/')"
      env:
        DOCKER_USERNAME: klakegg
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: make edge-tag edge-push

    - name: Publish templates
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/templates/*

    - name: Upload templates artifacts
      uses: actions/upload-artifact@v2
      if: "!startsWith(github.ref, 'refs/tags/')"
      with:
        name: templates
        path: target/templates/*