name: Docker build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: make build-docker

    - name: Test Docsy
      run: make test-docsy

    - name: Test DocuAPI
      run: make test-docuapi

    - name: Push egde images
      if: "!startsWith(github.ref, 'refs/tags/')"
      env:
        DOCKER_USERNAME: klakegg
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: make edge-tag edge-push
