name: Docker build

on:
  push:
    branches:
      - master
  release:
    types:
      - released

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    #- name: Set up Docker Buildx
    #  id: buildx
    #  uses: crazy-max/ghaction-docker-buildx@v3
    #  with:
    #    buildx-version: latest
    #    qemu-version: latest

    - name: Preprocess Dockerfile
      run: make dockerfile-import

    - name: Build
      run: make build

    - name: Upload target content
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target

    - name: Test Docsy
      run: make test-docsy

    - name: Test DocuAPI
      run: make test-docuapi
    
    - name: Docker login
      env:
        DOCKER_USERNAME: klakegg
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: make docker-login

    - name: Push egde images
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: make push-edge

    - name: Push images
      if: "startsWith(github.ref, 'refs/tags/')"
      run: make push-release
